[package]
name = "kcc"
version = "0.6.2"
edition = "2021"
authors = ["Maciej Mazur"]
description = "KarmazynOS own compiler (K0 → C). Stage0 host rustc builds kcc once; critical libs compile with kcc."
license = "MIT"
repository = "https://github.com/Maciej-EriAmo/KarmazynOs"

[[bin]]
name = "kcc"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
