//! K0 → C99 code generator.
//!
//! Foreign `cc`/`gcc` is **environment** (linking). **Frontend+IR→C is own compiler.**

use crate::ast::*;
use std::collections::HashMap;
use std::fmt::Write as _;

pub fn emit_c(prog: &Program, safe: bool) -> Result<String, String> {
    let mut out = String::new();
    writeln!(
        out,
        "/* generated by kcc (Karmazyn own compiler) — do not edit */"
    )
    .unwrap();
    writeln!(out, "#include <stdint.h>").unwrap();
    writeln!(out, "#include <stdbool.h>").unwrap();
    writeln!(out, "#include <math.h>").unwrap();
    writeln!(out, "#include <string.h>").unwrap();
    if safe {
        writeln!(out, "#include <stdlib.h>").unwrap();
    }
    writeln!(out).unwrap();

    for item in &prog.items {
        let Item::Fn(f) = item;
        if matches!(f.ret, Type::Array { .. }) {
            return Err(format!("fn {} cannot return array yet", f.name));
        }
        writeln!(out, "{};", fn_proto(f)?).unwrap();
    }
    writeln!(out).unwrap();

    for item in &prog.items {
        let Item::Fn(f) = item;
        emit_fn(&mut out, f, safe)?;
        writeln!(out).unwrap();
    }

    if prog
        .items
        .iter()
        .any(|i| matches!(i, Item::Fn(f) if f.name == "main"))
    {
        writeln!(out, "int main(void) {{ return (int)k0_main(); }}").unwrap();
    }
    Ok(out)
}

fn c_elem_type(t: &Type) -> Result<&'static str, String> {
    match t {
        Type::I32 => Ok("int32_t"),
        Type::I64 => Ok("int64_t"),
        Type::F64 => Ok("double"),
        Type::Bool => Ok("bool"),
        Type::Array { .. } => Err("nested array element".into()),
    }
}

fn c_type(t: &Type) -> Result<String, String> {
    match t {
        Type::Array { .. } => Err("use c_var_decl for arrays".into()),
        _ => Ok(c_elem_type(t)?.to_string()),
    }
}

fn c_var_decl(name: &str, t: &Type) -> Result<String, String> {
    let n = mangle_local(name);
    match t {
        Type::Array { elem, len } => {
            let e = c_elem_type(elem)?;
            Ok(format!("{e} {n}[{len}]"))
        }
        _ => Ok(format!("{} {n}", c_type(t)?)),
    }
}

fn fn_proto(f: &FnDef) -> Result<String, String> {
    let ret = c_type(&f.ret)?;
    let mut s = format!("{} k0_{}(", ret, f.name);
    for (i, (n, t)) in f.params.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        match t {
            Type::Array { elem, len: _ } => {
                let e = c_elem_type(elem)?;
                s.push_str(&format!("{e} *{}", mangle_local(n)));
            }
            _ => {
                s.push_str(&format!("{} {}", c_type(t)?, mangle_local(n)));
            }
        }
    }
    if f.params.is_empty() {
        s.push_str("void");
    }
    s.push(')');
    Ok(s)
}

fn mangle_local(n: &str) -> String {
    match n {
        "int" | "return" | "if" | "else" | "while" | "for" | "break" | "continue"
        | "true" | "false" => format!("k0_{n}"),
        _ => n.to_string(),
    }
}

struct Ctx {
    safe: bool,
    types: HashMap<String, Type>,
}

fn emit_fn(out: &mut String, f: &FnDef, safe: bool) -> Result<(), String> {
    let mut types = HashMap::new();
    for (n, t) in &f.params {
        types.insert(n.clone(), t.clone());
    }
    let mut ctx = Ctx { safe, types };
    writeln!(out, "{} {{", fn_proto(f)?).unwrap();
    emit_block(out, &f.body, 1, &mut ctx)?;
    writeln!(out, "}}").unwrap();
    Ok(())
}

fn emit_block(
    out: &mut String,
    b: &Block,
    indent: usize,
    ctx: &mut Ctx,
) -> Result<(), String> {
    let pad = "    ".repeat(indent);
    for st in &b.stmts {
        match st {
            Stmt::Let { name, ty, init } => {
                let t = match ty {
                    Some(t) => t.clone(),
                    None => {
                        let e = init.as_ref().ok_or("let without type needs init")?;
                        infer_type(e, &ctx.types)
                    }
                };
                match &t {
                    Type::Array { len, .. } => {
                        let decl = c_var_decl(name, &t)?;
                        writeln!(out, "{pad}{decl};").unwrap();
                        writeln!(
                            out,
                            "{}memset({}, 0, sizeof({}));",
                            pad,
                            mangle_local(name),
                            mangle_local(name)
                        )
                        .unwrap();
                        if init.is_some() {
                            return Err(format!(
                                "array let {name}[{len}]: zero-init only"
                            ));
                        }
                    }
                    _ => {
                        let e = init
                            .as_ref()
                            .ok_or_else(|| format!("let {name}: scalar requires initializer"))?;
                        writeln!(
                            out,
                            "{}{} = {};",
                            pad,
                            c_var_decl(name, &t)?,
                            emit_expr(e, ctx)?
                        )
                        .unwrap();
                    }
                }
                ctx.types.insert(name.clone(), t);
            }
            Stmt::Assign { name, value } => {
                writeln!(
                    out,
                    "{}{} = {};",
                    pad,
                    mangle_local(name),
                    emit_expr(value, ctx)?
                )
                .unwrap();
            }
            Stmt::IndexAssign { name, index, value } => {
                let idx = emit_expr(index, ctx)?;
                let val = emit_expr(value, ctx)?;
                let arr = mangle_local(name);
                if ctx.safe {
                    if let Some(Type::Array { len, .. }) = ctx.types.get(name) {
                        writeln!(
                            out,
                            "{}if (!((({idx}) >= 0) && (({idx}) < {len}))) abort();",
                            pad
                        )
                        .unwrap();
                    }
                }
                writeln!(out, "{pad}{arr}[{idx}] = {val};").unwrap();
            }
            Stmt::Return(None) => {
                writeln!(out, "{pad}return;").unwrap();
            }
            Stmt::Return(Some(e)) => {
                writeln!(out, "{}return {};", pad, emit_expr(e, ctx)?).unwrap();
            }
            Stmt::Expr(e) => {
                writeln!(out, "{}{};", pad, emit_expr(e, ctx)?).unwrap();
            }
            Stmt::If {
                cond,
                then_b,
                else_b,
            } => {
                writeln!(out, "{}if ({}) {{", pad, emit_expr(cond, ctx)?).unwrap();
                emit_block(out, then_b, indent + 1, ctx)?;
                write!(out, "{pad}}}").unwrap();
                if let Some(eb) = else_b {
                    writeln!(out, " else {{").unwrap();
                    emit_block(out, eb, indent + 1, ctx)?;
                    writeln!(out, "{pad}}}").unwrap();
                } else {
                    writeln!(out).unwrap();
                }
            }
            Stmt::While { cond, body } => {
                writeln!(out, "{}while ({}) {{", pad, emit_expr(cond, ctx)?).unwrap();
                emit_block(out, body, indent + 1, ctx)?;
                writeln!(out, "{pad}}}").unwrap();
            }
            Stmt::For {
                init,
                cond,
                step,
                body,
            } => {
                // Emit as C for: for (init; cond; step) { body }
                write!(out, "{pad}for (").unwrap();
                if let Some(ini) = init {
                    match ini.as_ref() {
                        Stmt::Let { name, ty, init: iv } => {
                            let t = match ty {
                                Some(t) => t.clone(),
                                None => {
                                    let e = iv.as_ref().ok_or("for-init let needs init")?;
                                    infer_type(e, &ctx.types)
                                }
                            };
                            if matches!(t, Type::Array { .. }) {
                                return Err("for-init array not supported".into());
                            }
                            let e = iv
                                .as_ref()
                                .ok_or("for-init scalar needs initializer")?;
                            write!(
                                out,
                                "{} = {}",
                                c_var_decl(name, &t)?,
                                emit_expr(e, ctx)?
                            )
                            .unwrap();
                            ctx.types.insert(name.clone(), t);
                        }
                        Stmt::Assign { name, value } => {
                            write!(
                                out,
                                "{} = {}",
                                mangle_local(name),
                                emit_expr(value, ctx)?
                            )
                            .unwrap();
                        }
                        Stmt::IndexAssign { name, index, value } => {
                            write!(
                                out,
                                "{}[{}] = {}",
                                mangle_local(name),
                                emit_expr(index, ctx)?,
                                emit_expr(value, ctx)?
                            )
                            .unwrap();
                        }
                        other => {
                            return Err(format!("unsupported for-init form: {other:?}"));
                        }
                    }
                }
                write!(out, "; ").unwrap();
                if let Some(c) = cond {
                    write!(out, "{}", emit_expr(c, ctx)?).unwrap();
                }
                write!(out, "; ").unwrap();
                if let Some(st) = step {
                    match st.as_ref() {
                        Stmt::Assign { name, value } => {
                            write!(
                                out,
                                "{} = {}",
                                mangle_local(name),
                                emit_expr(value, ctx)?
                            )
                            .unwrap();
                        }
                        Stmt::IndexAssign { name, index, value } => {
                            write!(
                                out,
                                "{}[{}] = {}",
                                mangle_local(name),
                                emit_expr(index, ctx)?,
                                emit_expr(value, ctx)?
                            )
                            .unwrap();
                        }
                        Stmt::Expr(e) => {
                            write!(out, "{}", emit_expr(e, ctx)?).unwrap();
                        }
                        other => {
                            return Err(format!("unsupported for-step form: {other:?}"));
                        }
                    }
                }
                writeln!(out, ") {{").unwrap();
                emit_block(out, body, indent + 1, ctx)?;
                writeln!(out, "{pad}}}").unwrap();
            }
            Stmt::Break => {
                writeln!(out, "{pad}break;").unwrap();
            }
            Stmt::Continue => {
                writeln!(out, "{pad}continue;").unwrap();
            }
        }
    }
    Ok(())
}

fn infer_type(e: &Expr, types: &HashMap<String, Type>) -> Type {
    match e {
        Expr::Int(_) => Type::I64,
        Expr::Float(_) => Type::F64,
        Expr::Bool(_) => Type::Bool,
        Expr::Ident(n) => types.get(n).cloned().unwrap_or(Type::I64),
        Expr::Unary { op: UnOp::Not, .. } => Type::Bool,
        Expr::Index { base, .. } => match base.as_ref() {
            Expr::Ident(n) => match types.get(n) {
                Some(Type::Array { elem, .. }) => *elem.clone(),
                _ => Type::I64,
            },
            _ => Type::I64,
        },
        Expr::Binary { op, left, right } => match op {
            BinOp::Eq | BinOp::Ne | BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge | BinOp::And
            | BinOp::Or => Type::Bool,
            _ => {
                let l = infer_type(left, types);
                let r = infer_type(right, types);
                if matches!(l, Type::F64) || matches!(r, Type::F64) {
                    Type::F64
                } else if matches!(l, Type::I64) || matches!(r, Type::I64) {
                    Type::I64
                } else {
                    Type::I32
                }
            }
        },
        _ => Type::I64,
    }
}

fn emit_expr(e: &Expr, ctx: &Ctx) -> Result<String, String> {
    Ok(match e {
        Expr::Int(n) => format!("{n}LL"),
        Expr::Float(f) => {
            if f.is_finite() {
                format!("{f}")
            } else {
                return Err("non-finite float literal".into());
            }
        }
        Expr::Bool(b) => {
            if *b {
                "true".into()
            } else {
                "false".into()
            }
        }
        Expr::Ident(n) => mangle_local(n),
        Expr::Index { base, index } => {
            let b = emit_expr(base, ctx)?;
            let i = emit_expr(index, ctx)?;
            if ctx.safe {
                if let Expr::Ident(name) = base.as_ref() {
                    if let Some(Type::Array { len, elem }) = ctx.types.get(name) {
                        let zero = match elem.as_ref() {
                            Type::F64 => "0.0",
                            Type::Bool => "false",
                            _ => "0",
                        };
                        // bounds-checked load
                        return Ok(format!(
                            "(((({i}) >= 0) && (({i}) < {len})) ? ({b}[{i}]) : (abort(), {zero}))"
                        ));
                    }
                }
            }
            format!("({b}[{i}])")
        }
        Expr::Unary { op, expr } => {
            let x = emit_expr(expr, ctx)?;
            match op {
                UnOp::Neg => format!("(-({x}))"),
                UnOp::Not => format!("(!({x}))"),
            }
        }
        Expr::Binary { op, left, right } => {
            let l = emit_expr(left, ctx)?;
            let r = emit_expr(right, ctx)?;
            if *op == BinOp::Rem {
                let lt = infer_type(left, &ctx.types);
                let rt = infer_type(right, &ctx.types);
                if matches!(lt, Type::F64) || matches!(rt, Type::F64) {
                    return Err("% not allowed on f64".into());
                }
            }
            let o = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Rem => "%",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
            };
            format!("(({l}) {o} ({r}))")
        }
        Expr::Call { name, args } => {
            let mut s = format!("k0_{name}(");
            for (i, a) in args.iter().enumerate() {
                if i > 0 {
                    s.push_str(", ");
                }
                s.push_str(&emit_expr(a, ctx)?);
            }
            s.push(')');
            s
        }
    })
}
