//! K0 → C99 code generator.
//!
//! Foreign `cc`/`gcc` is **environment** (linking). **Frontend+IR→C is own compiler.**

use crate::ast::*;
use std::fmt::Write as _;

pub fn emit_c(prog: &Program) -> Result<String, String> {
    let mut out = String::new();
    writeln!(out, "/* generated by kcc (Karmazyn own compiler) — do not edit */").unwrap();
    writeln!(out, "#include <stdint.h>").unwrap();
    writeln!(out, "#include <stdbool.h>").unwrap();
    writeln!(out, "#include <math.h>").unwrap();
    writeln!(out).unwrap();

    // forward decls
    for item in &prog.items {
        let Item::Fn(f) = item;
        writeln!(out, "{};", fn_proto(f)).unwrap();
    }
    writeln!(out).unwrap();

    for item in &prog.items {
        let Item::Fn(f) = item;
        emit_fn(&mut out, f)?;
        writeln!(out).unwrap();
    }

    // C process entry: K0 `fn main` → k0_main; provide real main for foreign linker.
    if prog.items.iter().any(|i| matches!(i, Item::Fn(f) if f.name == "main")) {
        writeln!(out, "int main(void) {{ return (int)k0_main(); }}").unwrap();
    }
    Ok(out)
}

fn c_type(t: &Type) -> &'static str {
    match t {
        Type::I32 => "int32_t",
        Type::I64 => "int64_t",
        Type::F64 => "double",
        Type::Bool => "bool",
    }
}

fn fn_proto(f: &FnDef) -> String {
    let mut s = format!("{} k0_{}(", c_type(&f.ret), f.name);
    for (i, (n, t)) in f.params.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&format!("{} {}", c_type(t), mangle_local(n)));
    }
    if f.params.is_empty() {
        s.push_str("void");
    }
    s.push(')');
    s
}

fn mangle_local(n: &str) -> String {
    // avoid clashing with C keywords
    match n {
        "int" | "return" | "if" | "else" | "while" | "true" | "false" => format!("k0_{n}"),
        _ => n.to_string(),
    }
}

fn emit_fn(out: &mut String, f: &FnDef) -> Result<(), String> {
    writeln!(out, "{} {{", fn_proto(f)).unwrap();
    emit_block(out, &f.body, 1)?;
    // if no return and non-void-ish, add default (i32/i64/bool/f64)
    writeln!(out, "}}").unwrap();
    Ok(())
}

fn emit_block(out: &mut String, b: &Block, indent: usize) -> Result<(), String> {
    let pad = "    ".repeat(indent);
    for st in &b.stmts {
        match st {
            Stmt::Let { name, ty, init } => {
                let t = ty.clone().unwrap_or_else(|| infer_type(init));
                writeln!(
                    out,
                    "{}{} {} = {};",
                    pad,
                    c_type(&t),
                    mangle_local(name),
                    emit_expr(init)?
                )
                .unwrap();
            }
            Stmt::Assign { name, value } => {
                writeln!(
                    out,
                    "{}{} = {};",
                    pad,
                    mangle_local(name),
                    emit_expr(value)?
                )
                .unwrap();
            }
            Stmt::Return(None) => {
                writeln!(out, "{pad}return;").unwrap();
            }
            Stmt::Return(Some(e)) => {
                writeln!(out, "{}return {};", pad, emit_expr(e)?).unwrap();
            }
            Stmt::Expr(e) => {
                writeln!(out, "{}{};", pad, emit_expr(e)?).unwrap();
            }
            Stmt::If {
                cond,
                then_b,
                else_b,
            } => {
                writeln!(out, "{}if ({}) {{", pad, emit_expr(cond)?).unwrap();
                emit_block(out, then_b, indent + 1)?;
                write!(out, "{pad}}}").unwrap();
                if let Some(eb) = else_b {
                    writeln!(out, " else {{").unwrap();
                    emit_block(out, eb, indent + 1)?;
                    writeln!(out, "{pad}}}").unwrap();
                } else {
                    writeln!(out).unwrap();
                }
            }
            Stmt::While { cond, body } => {
                writeln!(out, "{}while ({}) {{", pad, emit_expr(cond)?).unwrap();
                emit_block(out, body, indent + 1)?;
                writeln!(out, "{pad}}}").unwrap();
            }
        }
    }
    Ok(())
}

fn infer_type(e: &Expr) -> Type {
    match e {
        Expr::Int(_) => Type::I64,
        Expr::Float(_) => Type::F64,
        Expr::Bool(_) => Type::Bool,
        Expr::Unary { op: UnOp::Not, .. } => Type::Bool,
        Expr::Binary { op, left, right } => match op {
            BinOp::Eq | BinOp::Ne | BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge | BinOp::And
            | BinOp::Or => Type::Bool,
            _ => {
                let l = infer_type(left);
                let r = infer_type(right);
                if matches!(l, Type::F64) || matches!(r, Type::F64) {
                    Type::F64
                } else if matches!(l, Type::I64) || matches!(r, Type::I64) {
                    Type::I64
                } else {
                    Type::I32
                }
            }
        },
        _ => Type::I64,
    }
}

fn emit_expr(e: &Expr) -> Result<String, String> {
    Ok(match e {
        Expr::Int(n) => format!("{n}LL"),
        Expr::Float(f) => {
            if f.is_finite() {
                format!("{f}")
            } else {
                return Err("non-finite float literal".into());
            }
        }
        Expr::Bool(b) => {
            if *b {
                "true".into()
            } else {
                "false".into()
            }
        }
        Expr::Ident(n) => mangle_local(n),
        Expr::Unary { op, expr } => {
            let x = emit_expr(expr)?;
            match op {
                UnOp::Neg => format!("(-({x}))"),
                UnOp::Not => format!("(!({x}))"),
            }
        }
        Expr::Binary { op, left, right } => {
            let l = emit_expr(left)?;
            let r = emit_expr(right)?;
            let o = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Rem => "%",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
            };
            format!("(({l}) {o} ({r}))")
        }
        Expr::Call { name, args } => {
            let mut s = format!("k0_{name}(");
            for (i, a) in args.iter().enumerate() {
                if i > 0 {
                    s.push_str(", ");
                }
                s.push_str(&emit_expr(a)?);
            }
            s.push(')');
            s
        }
    })
}
