# Own-compiler gate (Tor B TB.1-TB.3):
#   stage0 rustc builds kcc; kcc builds critical .k0; golden law vs slab.
# Foreign: rustc (stage0), gcc (link), optional python for table golden.
# Own: kcc frontend+codegen + .k0 sources.
#
#   .\toolchain\verify_kcc.ps1

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
if (-not (Test-Path (Join-Path $Root "toolchain\kcc\Cargo.toml"))) {
    $Root = Split-Path -Parent $MyInvocation.MyCommand.Path
    $Root = Split-Path -Parent $Root
}
$Kcc = Join-Path $Root "toolchain\kcc"
$Out = Join-Path $Root "out\kcc"
$Slab = Join-Path $Root "native\karmazyn_slab"
New-Item -ItemType Directory -Force -Path $Out | Out-Null

Write-Host "=== kcc verify TB.1-TB.3 (own compiler) ===" -ForegroundColor Cyan
Write-Host "kcc crate: $Kcc"

Push-Location $Kcc
try {
    Write-Host ""
    Write-Host "[1] cargo test --release (stage0 rustc builds kcc)"
    cargo test --release
    if ($LASTEXITCODE -ne 0) { throw "cargo test failed" }

    Write-Host ""
    Write-Host "[2] cargo build --release"
    cargo build --release
    if ($LASTEXITCODE -ne 0) { throw "cargo build failed" }

    $exe = Join-Path $Kcc "target\release\kcc.exe"
    if (-not (Test-Path $exe)) { $exe = Join-Path $Kcc "target\release\kcc" }

    function Invoke-K0 {
        param([string]$srcName, [string]$binName)
        $src = Join-Path $Kcc "examples\$srcName"
        $cOut = Join-Path $Out ($binName + ".c")
        $bin = Join-Path $Out $binName
        Write-Host "  kcc $srcName"
        & $exe $src -o $cOut
        if ($LASTEXITCODE -ne 0) { throw "kcc emit $srcName failed" }
        & $exe $src --cc -o $bin
        if ($LASTEXITCODE -ne 0) { throw "kcc --cc $srcName failed" }
        $run = if (Test-Path "$bin.exe") { "$bin.exe" } else { $bin }
        & $run
        if ($LASTEXITCODE -ne 0) { throw "$binName exit $LASTEXITCODE" }
    }

    Write-Host ""
    Write-Host "[3] critical .k0 via kcc (own compiler)"
    Invoke-K0 "thermal.k0" "thermal_smoke"
    Invoke-K0 "tick_skeleton.k0" "tick_skeleton"
    Invoke-K0 "atom_table.k0" "atom_table"

    $cText = Get-Content (Join-Path $Out "thermal_smoke.c") -Raw
    if ($cText -notmatch "k0_state_code") { throw "C missing k0_state_code" }
    if ($cText -notmatch "generated by kcc") { throw "C missing kcc banner" }
} finally {
    Pop-Location
}

Write-Host ""
Write-Host "[4] Rust golden TB.3 (slab k0_state_code vs state_for_t)"
Push-Location $Slab
try {
    cargo test --release golden_k0
    if ($LASTEXITCODE -ne 0) { throw "slab golden_k0 failed" }
} finally {
    Pop-Location
}

Write-Host ""
Write-Host "[5] Python law table golden (optional)"
$py = Join-Path $Root "toolchain\golden_k0_thermal.py"
$pyCmd = Get-Command python -ErrorAction SilentlyContinue
if ($pyCmd) {
    & python $py
    if ($LASTEXITCODE -ne 0) { throw "python golden failed" }
} else {
    Write-Host "  skip (no python)" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "=== KCC_VERIFY_OK ===" -ForegroundColor Green
Write-Host "Own: kcc + .k0. Stage0: rustc (kcc+slab tests). Link: gcc. Golden: TB.3."
exit 0
