# TB.4 Phase 4 — self-host loop gate:
#   host kcc (stage0 rustc) builds K0 compiler dump;
#   dump emits guest C; foreign gcc links; binaries return eval results.
# Subset only (fn/let/return/+/-). Not a full kcc rewrite.
#
#   .\toolchain\verify_selfhost.ps1
# → KCC_SELFHOST_OK

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
if (-not (Test-Path (Join-Path $Root "toolchain\kcc\Cargo.toml"))) {
    $Root = Split-Path -Parent $MyInvocation.MyCommand.Path
    $Root = Split-Path -Parent $Root
}
$Kcc = Join-Path $Root "toolchain\kcc"
$Self = Join-Path $Root "toolchain\kcc_selfhost"
$Out = Join-Path $Root "out\kcc"
New-Item -ItemType Directory -Force -Path $Out | Out-Null

Write-Host "=== kcc verify TB.4 Phase 4 (self-host loop) ===" -ForegroundColor Cyan

Push-Location $Kcc
try {
    cargo build --release
    if ($LASTEXITCODE -ne 0) { throw "cargo build kcc failed" }
} finally {
    Pop-Location
}

$exe = Join-Path $Kcc "target\release\kcc.exe"
if (-not (Test-Path $exe)) { $exe = Join-Path $Kcc "target\release\kcc" }

Write-Host "[1] host kcc builds selfhost_dump.k0 (K0 compiler)"
$dumpSrc = Join-Path $Self "selfhost_dump.k0"
$dumpBin = Join-Path $Out "selfhost_dump"
& $exe $dumpSrc --safe --cc -o $dumpBin
if ($LASTEXITCODE -ne 0) { throw "kcc selfhost_dump failed" }
$dumpRun = if (Test-Path "$dumpBin.exe") { "$dumpBin.exe" } else { $dumpBin }

Write-Host "[2] K0 compiler dumps guest C bundle"
$bundle = Join-Path $Out "selfhost_bundle.c"
$p = Start-Process -FilePath $dumpRun -RedirectStandardOutput $bundle -NoNewWindow -Wait -PassThru
if ($p.ExitCode -ne 0) { throw "selfhost_dump exit $($p.ExitCode)" }
if (-not (Test-Path $bundle)) { throw "missing $bundle" }
$bundleText = [System.IO.File]::ReadAllText($bundle)
if ($bundleText -notmatch "generated by kcc-k0") { throw "bundle missing kcc-k0 banner" }
if ($bundleText -notmatch "#include <stdint.h>") { throw "bundle missing stdint.h" }

function Get-K0Section {
    param([string]$text, [string]$mark, [string[]]$rest)
    $idx = $text.IndexOf($mark)
    if ($idx -lt 0) { throw "missing marker $mark" }
    $start = $idx + $mark.Length
    while ($start -lt $text.Length -and ($text[$start] -eq "`r" -or $text[$start] -eq "`n")) {
        $start++
    }
    $end = $text.Length
    foreach ($m in $rest) {
        $n = $text.IndexOf($m, $start)
        if ($n -ge 0 -and $n -lt $end) { $end = $n }
    }
    return $text.Substring($start, $end - $start)
}

$secA = Get-K0Section $bundleText "#K0A" @("#K0B", "#K0C", "#K0E")
$secB = Get-K0Section $bundleText "#K0B" @("#K0C", "#K0E")
$secC = Get-K0Section $bundleText "#K0C" @("#K0E")
$secE = Get-K0Section $bundleText "#K0E" @()

function Invoke-GuestC {
    param([string]$name, [string]$src, [int]$expect)
    if ($src -notmatch "int main") { throw "$name C missing int main" }
    $cPath = Join-Path $Out ("selfhost_" + $name + ".c")
    $binPath = Join-Path $Out ("selfhost_" + $name)
    [System.IO.File]::WriteAllText($cPath, $src)
    $ccs = @("gcc", "clang", "cc")
    $linked = $false
    $last = ""
    foreach ($cc in $ccs) {
        & $cc $cPath -O2 -o $binPath 2>$null
        if ($LASTEXITCODE -eq 0) { $linked = $true; break }
        $last = "$cc exit $LASTEXITCODE"
    }
    if (-not $linked) { throw "link $name failed ($last)" }
    $run = if (Test-Path "$binPath.exe") { "$binPath.exe" } else { $binPath }
    & $run
    if ($LASTEXITCODE -ne $expect) {
        throw "$name expected exit $expect, got $LASTEXITCODE"
    }
    Write-Host "  $name -> exit $expect OK"
}

Write-Host "[3] gcc guest C from K0 emit + run"
Invoke-GuestC "A" $secA 42
Invoke-GuestC "B" $secB 1
Invoke-GuestC "C" $secC 3
Invoke-GuestC "E" $secE 15

Write-Host ""
Write-Host "=== KCC_SELFHOST_OK ===" -ForegroundColor Green
Write-Host "Loop: host kcc → K0 emit → gcc → run. Subset A/B/C/E; D rejected in dump."
exit 0
