# Own-compiler gate (Tor B TB.1–TB.3d+ + TB.4 Phase 0–3):
#   stage0 rustc builds kcc; kcc builds critical .k0; golden law vs slab;
#   structs; self-host: tok_kind + lex_buffer + parse_mini + emit_mini.
# Foreign: rustc (stage0), gcc (link), optional python for table golden.
# Own: kcc frontend+codegen + .k0 sources.
#
#   .\toolchain\verify_kcc.ps1

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
if (-not (Test-Path (Join-Path $Root "toolchain\kcc\Cargo.toml"))) {
    $Root = Split-Path -Parent $MyInvocation.MyCommand.Path
    $Root = Split-Path -Parent $Root
}
$Kcc = Join-Path $Root "toolchain\kcc"
$Out = Join-Path $Root "out\kcc"
$Slab = Join-Path $Root "native\karmazyn_slab"
New-Item -ItemType Directory -Force -Path $Out | Out-Null

Write-Host "=== kcc verify TB.1-TB.3d+ / TB.4 Phase0-3 (own compiler) ===" -ForegroundColor Cyan
Write-Host "kcc crate: $Kcc"

Push-Location $Kcc
try {
    Write-Host ""
    Write-Host "[1] cargo test --release (stage0 rustc builds kcc)"
    cargo test --release
    if ($LASTEXITCODE -ne 0) { throw "cargo test failed" }

    Write-Host ""
    Write-Host "[2] cargo build --release"
    cargo build --release
    if ($LASTEXITCODE -ne 0) { throw "cargo build failed" }

    $exe = Join-Path $Kcc "target\release\kcc.exe"
    if (-not (Test-Path $exe)) { $exe = Join-Path $Kcc "target\release\kcc" }

    function Invoke-K0 {
        param([string]$srcName, [string]$binName)
        $src = Join-Path $Kcc "examples\$srcName"
        $cOut = Join-Path $Out ($binName + ".c")
        $bin = Join-Path $Out $binName
        Write-Host "  kcc $srcName (--safe)"
        # single pass: semantic check + safe bounds + --cc link
        & $exe $src --safe --cc -o $bin
        if ($LASTEXITCODE -ne 0) { throw "kcc --safe --cc $srcName failed" }
        if (-not (Test-Path $cOut)) { throw "missing generated C: $cOut" }
        $cText = Get-Content $cOut -Raw
        if ($cText -notmatch "generated by kcc") { throw "missing kcc banner in $cOut" }
        # programs that index arrays must emit abort() under --safe
        if ($cText -match "\[[^\]]+\]\s*=" -or $cText -match "\]\)") {
            if ($srcName -match "atom_table|store_mini") {
                if ($cText -notmatch "abort") { throw "safe mode missing abort in $cOut" }
            }
        }
        $run = if (Test-Path "$bin.exe") { "$bin.exe" } else { $bin }
        & $run
        if ($LASTEXITCODE -ne 0) { throw "$binName exit $LASTEXITCODE" }
    }

    Write-Host ""
    Write-Host "[3] critical .k0 via kcc (own compiler)"
    Invoke-K0 "thermal.k0" "thermal_smoke"
    Invoke-K0 "tick_skeleton.k0" "tick_skeleton"
    Invoke-K0 "atom_table.k0" "atom_table"
    Invoke-K0 "store_mini.k0" "store_mini"

    # TB.3d+ structs — nested + return-struct; exit 50 (15+20+5+10)
    Write-Host "  kcc struct_point.k0 (--safe) expect exit 50"
    $spSrc = Join-Path $Kcc "examples\struct_point.k0"
    $spBin = Join-Path $Out "struct_point"
    & $exe $spSrc --safe --cc -o $spBin
    if ($LASTEXITCODE -ne 0) { throw "kcc struct_point failed" }
    $spRun = if (Test-Path "$spBin.exe") { "$spBin.exe" } else { $spBin }
    & $spRun
    if ($LASTEXITCODE -ne 50) { throw "struct_point expected exit 50, got $LASTEXITCODE" }
    $spC = Get-Content (Join-Path $Out "struct_point.c") -Raw
    if ($spC -notmatch "typedef struct Point") { throw "struct_point.c missing typedef" }
    if ($spC -notmatch "typedef struct Rect") { throw "struct_point.c missing nested Rect" }
    if ($spC -notmatch "Point k0_make_point") { throw "struct_point.c missing return-struct" }

    # TB.4 Phase 0/1 — self-host seed (host kcc builds K0 lexer pieces)
    Write-Host "  kcc tok_kind.k0 (TB.4 Phase 0) expect exit 0"
    $tkSrc = Join-Path $Root "toolchain\kcc_selfhost\tok_kind.k0"
    $tkBin = Join-Path $Out "tok_kind"
    & $exe $tkSrc --safe --cc -o $tkBin
    if ($LASTEXITCODE -ne 0) { throw "kcc tok_kind failed" }
    $tkRun = if (Test-Path "$tkBin.exe") { "$tkBin.exe" } else { $tkBin }
    & $tkRun
    if ($LASTEXITCODE -ne 0) { throw "tok_kind expected exit 0, got $LASTEXITCODE" }

    Write-Host "  kcc lex_buffer.k0 (TB.4 Phase 1) expect exit 0"
    $lbSrc = Join-Path $Root "toolchain\kcc_selfhost\lex_buffer.k0"
    $lbBin = Join-Path $Out "lex_buffer"
    & $exe $lbSrc --safe --cc -o $lbBin
    if ($LASTEXITCODE -ne 0) { throw "kcc lex_buffer failed" }
    $lbRun = if (Test-Path "$lbBin.exe") { "$lbBin.exe" } else { $lbBin }
    & $lbRun
    if ($LASTEXITCODE -ne 0) { throw "lex_buffer expected exit 0, got $LASTEXITCODE" }

    Write-Host "  kcc parse_mini.k0 (TB.4 Phase 2) expect exit 0"
    $pmSrc = Join-Path $Root "toolchain\kcc_selfhost\parse_mini.k0"
    $pmBin = Join-Path $Out "parse_mini"
    & $exe $pmSrc --safe --cc -o $pmBin
    if ($LASTEXITCODE -ne 0) { throw "kcc parse_mini failed" }
    $pmRun = if (Test-Path "$pmBin.exe") { "$pmBin.exe" } else { $pmBin }
    & $pmRun
    if ($LASTEXITCODE -ne 0) { throw "parse_mini expected exit 0, got $LASTEXITCODE" }

    Write-Host "  kcc emit_mini.k0 (TB.4 Phase 3) expect exit 0"
    $emSrc = Join-Path $Root "toolchain\kcc_selfhost\emit_mini.k0"
    $emBin = Join-Path $Out "emit_mini"
    & $exe $emSrc --safe --cc -o $emBin
    if ($LASTEXITCODE -ne 0) { throw "kcc emit_mini failed" }
    $emRun = if (Test-Path "$emBin.exe") { "$emBin.exe" } else { $emBin }
    & $emRun
    if ($LASTEXITCODE -ne 0) { throw "emit_mini expected exit 0, got $LASTEXITCODE" }

    $cText = Get-Content (Join-Path $Out "thermal_smoke.c") -Raw
    if ($cText -notmatch "k0_state_code") { throw "C missing k0_state_code" }
    $cStore = Get-Content (Join-Path $Out "store_mini.c") -Raw
    if ($cStore -notmatch "abort") { throw "store_mini.c --safe must contain abort bounds" }
} finally {
    Pop-Location
}

Write-Host ""
Write-Host "[4] Rust golden TB.3/TB.3b (thermal + store_mini reach vs slab)"
Push-Location $Slab
try {
    cargo test --release golden_k0
    if ($LASTEXITCODE -ne 0) { throw "slab golden_k0 failed" }
} finally {
    Pop-Location
}

Write-Host ""
Write-Host "[5] Python law table golden (optional)"
$py = Join-Path $Root "toolchain\golden_k0_thermal.py"
$pyCmd = Get-Command python -ErrorAction SilentlyContinue
if ($pyCmd) {
    & python $py
    if ($LASTEXITCODE -ne 0) { throw "python golden failed" }
} else {
    Write-Host "  skip (no python)" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "=== KCC_VERIFY_OK ===" -ForegroundColor Green
Write-Host "Own: kcc + .k0. Stage0: rustc (kcc+slab tests). Link: gcc. Golden: TB.3/3b + structs + TB.4 P0-3."
exit 0
